// Maps the icon names used across the app (Material Icons / Font Awesome)
// to Lucide icons served from /icons/lucide.svg.
// Names not listed here keep their original icon font.
// Regenerate the sprite with tools/build-lucide-sprite.py after adding names.

const map = {
  "__nav_agents": "monitor-cog",
  "__nav_alerts": "bell-ring",
  "__nav_audit": "scroll-text",
  "__nav_automation": "workflow",
  "__nav_boot": "power",
  "__nav_bulk": "layers",
  "__nav_cards": "layout-grid",
  "__nav_clients": "building-complex",
  "__nav_clock": "clock",
  "__nav_close_panel": "panel-right-close",
  "__nav_codesign": "file-lock",
  "__nav_command": "command",
  "__nav_dashboard": "layout-grid",
  "__nav_debug": "bug",
  "__nav_deploy": "rocket",
  "__nav_failing": "circle-x",
  "__nav_help": "life-buoy",
  "__nav_install": "circle-plus",
  "__nav_maint": "construction",
  "__nav_maintenance": "hammer",
  "__nav_maximize": "maximize-2",
  "__nav_more": "ellipsis",
  "__nav_offline": "wifi-off",
  "__nav_ok": "circle-check",
  "__nav_online": "wifi",
  "__nav_panel": "panel-left",
  "__nav_patches": "shield-alert",
  "__nav_pending": "list-todo",
  "__nav_permissions": "shield-check",
  "__nav_reboot": "rotate-ccw",
  "__nav_reporting": "chart-no-axes-combined",
  "__nav_scripts": "file-code",
  "__nav_server": "server",
  "__nav_settings": "settings-2",
  "__nav_sort": "arrow-up-down",
  "__nav_table": "table-2",
  "__nav_update": "circle-arrow-up",
  "__nav_user": "user",
  "__nav_users": "users",
  "__nav_warning": "triangle-alert",
  "__nav_workstation": "monitor",
  "access_time": "clock",
  "account_tree": "network",
  "add": "plus",
  "add_chart": "chart-column",
  "alarm_off": "alarm-clock-off",
  "analytics": "chart-column",
  "apartment": "building",
  "apps": "layout-grid",
  "arrow_back": "arrow-left",
  "arrow_downward": "arrow-down",
  "arrow_drop_down": "chevron-down",
  "arrow_drop_up": "chevron-up",
  "arrow_forward": "arrow-right",
  "arrow_upward": "arrow-up",
  "attach_file": "paperclip",
  "autorenew": "refresh-cw",
  "bug_report": "bug",
  "build": "wrench",
  "business": "building-complex",
  "cached": "refresh-cw",
  "cancel": "circle-x",
  "check": "check",
  "check_circle": "circle-check",
  "chevron_left": "chevron-left",
  "chevron_right": "chevron-right",
  "clear": "x",
  "close": "x",
  "cloud_download": "cloud-download",
  "cloud_upload": "cloud-upload",
  "code": "code",
  "computer": "monitor",
  "construction": "construction",
  "content_copy": "copy",
  "crop_square": "square",
  "dark_mode": "moon",
  "dashboard": "layout-dashboard",
  "delete": "trash",
  "description": "file-text",
  "devices": "monitor-smartphone",
  "dns": "server",
  "done": "check",
  "download": "download",
  "drag_handle": "grip-horizontal",
  "edit": "pencil",
  "email": "mail",
  "error": "circle-alert",
  "error_outline": "circle-alert",
  "event": "calendar",
  "expand_less": "chevron-up",
  "expand_more": "chevron-down",
  "fa-solid fa-barcode": "barcode",
  "fa-solid fa-display": "monitor",
  "fa-solid fa-file-import": "file-input",
  "far fa-clock": "clock",
  "far fa-folder-open": "folder-open",
  "far fa-hdd": "hard-drive",
  "far fa-sticky-note": "sticky-note",
  "fas fa-ban": "ban",
  "fas fa-barcode": "barcode",
  "fas fa-chart-area": "chart-area",
  "fas fa-check": "check",
  "fas fa-check-circle": "circle-check",
  "fas fa-check-double": "check-check",
  "fas fa-clipboard-list": "clipboard-list",
  "fas fa-cogs": "cog",
  "fas fa-desktop": "monitor",
  "fas fa-edit": "pencil",
  "fas fa-exclamation": "circle-alert",
  "fas fa-first-aid": "briefcase-medical",
  "fas fa-globe-americas": "globe",
  "fas fa-home": "house",
  "fas fa-info-circle": "info",
  "fas fa-memory": "memory-stick",
  "fas fa-microchip": "cpu",
  "fas fa-network-wired": "network",
  "fas fa-plus": "plus",
  "fas fa-power-off": "power",
  "fas fa-server": "server",
  "fas fa-signal": "signal",
  "fas fa-tasks": "list-checks",
  "fas fa-terminal": "terminal",
  "fas fa-trash-alt": "trash",
  "fas fa-tv": "tv",
  "fas fa-user": "user",
  "file_download": "download",
  "file_upload": "upload",
  "filter_alt": "funnel",
  "first_page": "chevrons-left",
  "flag": "flag",
  "folder": "folder",
  "folder_open": "folder-open",
  "groups": "users",
  "help": "circle-question-mark",
  "help_outline": "circle-question-mark",
  "history": "rotate-ccw-clock",
  "image": "image",
  "info": "info",
  "insert_drive_file": "file",
  "insights": "chart-line",
  "keyboard": "keyboard",
  "keyboard_arrow_down": "chevron-down",
  "keyboard_arrow_left": "chevron-left",
  "keyboard_arrow_right": "chevron-right",
  "keyboard_arrow_up": "chevron-up",
  "last_page": "chevrons-right",
  "light_mode": "sun",
  "link": "link",
  "lock": "lock",
  "logout": "log-out",
  "menu": "menu",
  "more_horiz": "ellipsis",
  "more_vert": "ellipsis-vertical",
  "nights_stay": "moon",
  "notifications": "bell",
  "offline_bolt": "zap-off",
  "open_in_new": "external-link",
  "people": "users",
  "person": "user",
  "phone_android": "smartphone",
  "play_arrow": "play",
  "policy": "shield-check",
  "power": "plug",
  "power_off": "power-off",
  "power_settings_new": "power",
  "redo": "redo-2",
  "refresh": "refresh-cw",
  "remove": "minus",
  "remove_circle_outline": "circle-minus",
  "remove_red_eye": "eye",
  "restart_alt": "rotate-ccw",
  "save": "save",
  "schedule": "clock",
  "screen_share": "screen-share",
  "search": "search",
  "security": "shield",
  "send": "send",
  "settings": "settings",
  "shield": "shield",
  "snooze": "alarm-clock-off",
  "star": "star",
  "star_outline": "star",
  "stop": "square",
  "sync": "refresh-cw",
  "system_update": "monitor-down",
  "terminal": "square-terminal",
  "today": "calendar",
  "travel_explore": "scan-search",
  "tune": "sliders-horizontal",
  "undo": "undo-2",
  "update": "rotate-cw",
  "upload": "upload",
  "usb": "usb",
  "verified_user": "shield-check",
  "visibility": "eye",
  "visibility_off": "eye-off",
  "vpn_key": "key-round",
  "warning": "triangle-alert",
  "wb_sunny": "sun"
};

const SPRITE = "/icons/lucide.svg";

export function lucide(name) {
  return `svguse:${SPRITE}#${name}|0 0 24 24`;
}

// helper for app code: nav("users") -> the icon string for a __nav_ key
export function navIcon(key) {
  return lucide(map[`__nav_${key}`] || key);
}

export default function iconMapFn(iconName) {
  const target = map[iconName];
  if (target !== undefined) return { icon: lucide(target) };
}
